# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib /home/mikel/Desktop/Decoder_3_8/Decoder_3_8.srcs/sources_1/new/Decoder.v
read_xdc /home/mikel/Desktop/Decoder_3_8/Decoder_3_8.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/mikel/Desktop/Decoder_3_8/Decoder_3_8.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mikel/Desktop/Decoder_3_8/Decoder_3_8.cache/wt [current_project]
set_property parent.project_dir /home/mikel/Desktop/Decoder_3_8 [current_project]
catch { write_hwdef -file Decoder.hwdef }
synth_design -top Decoder -part xc7a100tcsg324-1
write_checkpoint Decoder.dcp
report_utilization -file Decoder_utilization_synth.rpt -pb Decoder_utilization_synth.pb
