# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  /home/mikel/Desktop/7_seg_disp/7_seg_disp.srcs/sources_1/new/mux.v
  /home/mikel/Desktop/7_seg_disp/7_seg_disp.srcs/sources_1/new/counter.v
  /home/mikel/Desktop/7_seg_disp/7_seg_disp.srcs/sources_1/new/7_seg.v
  /home/mikel/Desktop/7_seg_disp/7_seg_disp.srcs/sources_1/new/wrapper.v
}
read_xdc /home/mikel/Desktop/7_seg_disp/7_seg_disp.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/mikel/Desktop/7_seg_disp/7_seg_disp.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mikel/Desktop/7_seg_disp/7_seg_disp.cache/wt [current_project]
set_property parent.project_dir /home/mikel/Desktop/7_seg_disp [current_project]
catch { write_hwdef -file wrapper.hwdef }
synth_design -top wrapper -part xc7a100tcsg324-1
write_checkpoint wrapper.dcp
report_utilization -file wrapper_utilization_synth.rpt -pb wrapper_utilization_synth.pb
