# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  {/home/mikel/Desktop/Project 6/Project 6.2/Count_clk_div/Count_clk_div.srcs/sources_1/new/Counter.v}
  {/home/mikel/Desktop/Project 6/Project 6.2/Count_clk_div/Count_clk_div.srcs/sources_1/new/ClkDivider.v}
  {/home/mikel/Desktop/Project 6/Project 6.2/Count_clk_div/Count_clk_div.srcs/sources_1/new/Wrapper.v}
}
read_xdc {{/home/mikel/Desktop/Project 6/Project 6.2/Count_clk_div/Count_clk_div.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{/home/mikel/Desktop/Project 6/Project 6.2/Count_clk_div/Count_clk_div.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc}}]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/mikel/Desktop/Project 6/Project 6.2/Count_clk_div/Count_clk_div.cache/wt} [current_project]
set_property parent.project_dir {/home/mikel/Desktop/Project 6/Project 6.2/Count_clk_div} [current_project]
catch { write_hwdef -file Wrapper.hwdef }
synth_design -top Wrapper -part xc7a100tcsg324-1
write_checkpoint Wrapper.dcp
report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb
