# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib /home/mikel/Desktop/Shifter_4in/Shifter_4in.srcs/sources_1/new/Shifter_4in.v
read_xdc /home/mikel/Desktop/Shifter_4in/Shifter_4in.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /home/mikel/Desktop/Shifter_4in/Shifter_4in.srcs/constrs_1/imports/Desktop/Nexys4_Master.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mikel/Desktop/Shifter_4in/Shifter_4in.cache/wt [current_project]
set_property parent.project_dir /home/mikel/Desktop/Shifter_4in [current_project]
catch { write_hwdef -file Shifter_4in.hwdef }
synth_design -top Shifter_4in -part xc7a100tcsg324-1
write_checkpoint Shifter_4in.dcp
report_utilization -file Shifter_4in_utilization_synth.rpt -pb Shifter_4in_utilization_synth.pb
